name: signtaxi_app
description: "SignTaxi - Book taxis on demand"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  pinput: ^4.0.0
  provider: ^6.1.1
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.3
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/illustrations/isometric_taxi.svg
    - assets/illustrations/city_skyline.png
    - assets/theme.json
    - assets/images/taxi1.jpg
    - assets/images/taxi2.jpg
    - assets/images/taxi3.jpg
    - assets/images/corporate_left.jpg
    - assets/images/suv.jpg
    - assets/images/pink.jpg
    - assets/images/traveller.jpg
    - assets/images/sedan.jpg
    - assets/images/mini.jpg
